### ISSUE TITLE
RPC-Explorer

### ISSUE THREAD

**Issue by jaonoctus** [jamaljsr/polar#457]
I'm trying to connect the [RPC-Explorer](https://github.com/janoside/btc-rpc-explorer) to a node.

```
regtest_explorer | 2021-04-29T09:01:56.371Z btcexp:app Starting BTC RPC Explorer, v3.1.1 at http://0.0.0.0:3002/
regtest_explorer | 2021-04-29T09:01:56.371Z btcexp:app Connecting to RPC node at 127.0.0.1:18443
regtest_explorer | 2021-04-29T09:01:56.378Z btcexp:app Verifying RPC connection...
regtest_explorer | 2021-04-29T09:01:56.379Z btcexp:app Loading mining pools config
regtest_explorer | 2021-04-29T09:01:56.393Z btcexp:error Error 9u4278t5h7rfhgf: Error: RpcError: type=failure-01, json: {"userData":{"error":{"cause":{"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":18443},"isOperational":true,"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":18443},"request":"getnetworkinfo"}}, userData: [object Object] (json: {"error":{"cause":{"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":18443},"isOperational":true,"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":18443},"request":"getnetworkinfo"})
regtest_explorer | 2021-04-29T09:01:56.393Z btcexp:error Error 9u4278t5h7rfhgf: Error: RpcError: type=failure-01, json: {"userData":{"error":{"cause":{"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":18443},"isOperational":true,"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":18443},"request":"getblockchaininfo"}}, userData: [object Object] (json: {"error":{"cause":{"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":18443},"isOperational":true,"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":18443},"request":"getblockchaininfo"})
regtest_explorer | 2021-04-29T09:01:56.394Z btcexp:error Error 32ugegdfsde: Error: RpcError: type=failure-01, json: {"userData":{"error":{"cause":{"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":18443},"isOperational":true,"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":18443},"request":"getnetworkinfo"}}
```

**To Reproduce**

Explorer **docker-compose.yml**

```yml
version: '3.4'

services:
  rpc-explorer:
    container_name: regtest_explorer
    image: getumbrel/btc-rpc-explorer:v3.1.1
    ports:
      - "3002:3002"
    environment:
      BTCEXP_HOST: 0.0.0.0
      BTCEXP_BITCOIND_URI: "bitcoin://polaruser:polarpass@127.0.0.1:18443?timeout=10000"
networks:
  default:
    external:
      name: 1_default
```

**Expected behavior**
Should be able to connect via RPC credentials

**Screenshots**
![image](https://user-images.githubusercontent.com/7918067/116526985-8db39880-a8b0-11eb-85e2-12cd87a39abd.png)

**Desktop:**
- OS: Ubuntu 20.10 64-bit
- Polar Version: 1.2.0
- Docker Version: 19.03.13
- Docker Compose Version: 1.28.5, build c4eb3a1f
