### ISSUE TITLE
Feature Request: Define persistent docker network

### ISSUE THREAD

**Issue by bjarnemagnussen** [jamaljsr/polar#525]
**Is your feature request related to a problem? Please describe.**
I am trying out LND's remote db backend support (using postgres). However, since I cannot just via the GUI add a postgres service (or any other external service that may be supported in the future) and supporting each such service feels a bit overkill, I was thinking about an easy way to handle this better. 

**Describe the solution you'd like**
It may therefore be nice to be able to define a persistent external docker network that must be used for a Polar environment, instead of Polar creating a deleting a specific default network with each start and stop. This would allow for additional services (e.g. postgres) to be spun up external/independent to Polar, while the nodes in the polar environment can make use of it.

**Additional context**
Currently I have solved this by creating a standalone docker-compose file that spins up postgres and uses the docker network created by Polar automatically (e.g. `2_default` for environment 2). 

Naturally, this requires that always first start Polar, as otherwise the network is not created yet.

When I want to stop the environment I have to first stop postgres, as Polar will try to delete the network it created when pressing the STOP button, which is impossible if any service is still running in this network.

Docker-compose file for my postgres service, which assumes polar network 2 exists:
```
version: '3.3'
services:
  postgres1:
    image: postgres:latest
    container_name: polar-n2-postgres1
    hostname: postgres1
    restart: always
    volumes:
      - ./networks/2/volumes/db/postgres1:/var/lib/postgresql/data
    expose:
      - '5432'
    ports:
      - '45432:5432'
    environment:
      POSTGRES_PASSWORD: lnd
      POSTGRES_USER: lnd

networks:
  default:
    external: true
    name: 2_default
```

**Comment by jamaljsr** [comment]
Thanks for the feedback and providing the details of your use case. What you're asking for makes total sense and I don't think it would be a huge amount of effort to implement.

My initial thought is that we add an additional field when creating a new Polar network. This field would allow you to specify an external Docker network to use. If a value is entered, then it will be paced into the docker-compose.yml file created by Polar, similar to what yo have above. Since the Docker network is external, Docker shouldn't attempt to delete it when stopping the Polar network.

Does this sound like a reasonable UX to you?

**Comment by bjarnemagnussen** [comment]
Thanks! That sounds fantastic and would be very helpful to me!

**Comment by amovfx** [comment]
I'm going to take a stab at this.

**Comment by amovfx** [comment]
Here is an example  docker-compose file of what I have polar producing. The external network name is formated polar-${Network.name}

```
version: '3.3'
name: External
services:
  ....
networks:
  default:
    external: true
    name: polar-External
```
